version: '3.7'

services:
  web:
    build: .
    command: python /code/config/manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
