# Generated by Django 4.1.4 on 2023-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepwork',
            name='self_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deepwork',
            name='work_hours',
            field=models.IntegerField(default=0),
        ),
    ]
