# Generated by Django 4.2 on 2023-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepwork', '0002_alter_deepwork_self_hours_alter_deepwork_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepwork',
            name='officework_done',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepwork',
            name='studytopics_covered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
