# Generated by Django 4.1.1 on 2022-09-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('completion_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=100)),
                ('effort_hours', models.PositiveIntegerField(default=10)),
                ('completion_date', models.DateTimeField(auto_now=True)),
                ('time_spent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(auto_now=True)),
                ('effort_hours', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(max_length=50)),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('time_spent', models.PositiveIntegerField(default=2)),
                ('content_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('status', models.CharField(max_length=100)),
                ('objectives', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.objective')),
            ],
        ),
    ]
