# Generated by Django 4.1.1 on 2022-09-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_task_end_time_task_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='objective',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
