# Generated by Django 4.1.1 on 2022-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_alter_objective_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
