# Generated by Django 4.1.1 on 2022-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_alter_objective_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
