# Generated by Django 4.1.1 on 2022-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_alter_objective_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
