# Generated by Django 4.1.1 on 2022-09-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0007_alter_objective_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goal",
            name="objectives",
        ),
        migrations.AddField(
            model_name="objective",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="track.goal",
            ),
        ),
    ]
