# Generated by Django 4.1.1 on 2022-10-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0008_remove_goal_objectives_objective_goal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
