# Generated by Django 4.1.1 on 2022-10-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0009_announcements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcements",
            name="date_added",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_completed",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(default="not-started", max_length=50),
        ),
    ]
