# Generated by Django 4.1.1 on 2022-10-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0010_alter_announcements_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
