# Generated by Django 4.1.1 on 2022-10-02 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0011_alter_task_date_completed_alter_task_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(
                blank=True, default=datetime.time(4, 45, 47, 286630), null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(4, 45, 47, 286615), null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_spent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
