# Generated by Django 4.1.1 on 2022-10-02 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0012_alter_task_end_time_alter_task_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(
                blank=True, default=datetime.time(4, 50, 13, 271093), null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(4, 50, 13, 271078), null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_spent",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
