# Generated by Django 4.1.1 on 2022-10-02 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0014_alter_task_end_time_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_time",
            field=models.TimeField(
                blank=True, default=datetime.time(5, 16, 6, 261531), null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_time",
            field=models.TimeField(
                blank=True, default=datetime.time(5, 16, 6, 261520), null=True
            ),
        ),
    ]
