# Generated by Django 4.1.1 on 2022-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0016_alter_task_end_time_alter_task_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="time_spent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
