# Generated by Django 4.1.1 on 2022-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0017_alter_task_time_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(),
        ),
    ]
