# Generated by Django 4.1.1 on 2022-10-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0018_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(),
        ),
    ]
