# Generated by Django 4.1.1 on 2022-10-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0019_alter_project_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
