# Generated by Django 4.1.1 on 2022-10-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0020_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
