# Generated by Django 4.1.1 on 2022-11-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0021_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
