# Generated by Django 4.1.4 on 2022-12-16 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0024_rename_content_id_task_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 16, 9, 26, 59, 304057, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
