# Generated by Django 4.1.4 on 2022-12-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0026_remove_task_effort_hours_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort_hours',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
