# Generated by Django 4.1.4 on 2022-12-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_rename_sprint1_sprint'),
        ('track', '0031_alter_task_date_completed_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprint.sprint'),
        ),
    ]
