# Generated by Django 4.1.4 on 2022-12-31 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_alter_sprint_comments_alter_sprint_end_date_and_more'),
        ('track', '0032_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='sprint.sprint'),
        ),
    ]
