# Generated by Django 4.1.4 on 2023-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0033_alter_task_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='weblink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
