# Generated by Django 4.1.4 on 2023-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0034_task_weblink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='weblink',
        ),
        migrations.AddField(
            model_name='objective',
            name='weblink',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
