# Generated by Django 4.1.4 on 2023-02-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0035_remove_task_weblink_objective_weblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_objectives', to='track.goal'),
        ),
    ]
