# Generated by Django 4.1.4 on 2023-02-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0036_alter_objective_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='effort_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
