# Generated by Django 4.1.4 on 2023-02-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0037_objective_effort_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
