# Generated by Django 4.1.4 on 2023-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0038_alter_task_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='effort_left',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
