# Generated by Django 4.1.4 on 2023-02-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0039_task_effort_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='effort_left',
        ),
        migrations.AddField(
            model_name='objective',
            name='effort_left',
            field=models.FloatField(default=0.0),
        ),
    ]
