# Generated by Django 4.1.4 on 2023-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0040_remove_task_effort_left_objective_effort_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
