# Generated by Django 4.1.4 on 2023-03-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0041_objective_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
