# Generated by Django 4.1.4 on 2023-03-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0042_goal_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='weblink',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
