# Generated by Django 4.1.4 on 2022-12-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not-started', 'not-started'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='not-started', max_length=50)),
                ('comments', models.TextField(max_length=255)),
            ],
        ),
    ]
