# Generated by Django 4.1.4 on 2022-12-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sprint1',
            new_name='Sprint',
        ),
    ]
