# Generated by Django 4.1.4 on 2022-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_rename_sprint1_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='comments',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(),
        ),
    ]
